---

- name: AWS Infrastructure
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Validate parameters
      assert:
        that:
          - jenkins_stack is defined
          - aws_region is defined
#          - tooling_environment is defined
#
#    - set_fact:
#        app_name: docker-datacenter
#        ucp_manager_name: docker-manager
#        dtr_node_name: docker-dtr
#        tooling_environment: prod # This is required for aws_facts
#        dtr_http_port: 80
#        dtr_https_port: 443
#        route53_domain: icaptools


#- hosts: jenkins_masters[0],jenkis_slaves[0]
- hosts: jenkis_slaves[0]
  remote_user: ec2-user
  become: yes
  become_user: root
  roles:
    - role: digital_common
#  tasks:
#    - pause:



- hosts: jenkins_slaves[0]
  remote_user: devops
  become: yes
  become_user: root
  roles:
    - role: jenkins_slave



#- hosts: jenkins_masters[0]
#  remote_user: devops
#  become: yes
#  become_user: root
#  roles:
#    - role: jenkins_master
