---

- name: Set RHEL User Facts
  set_fact:
    devops_user_groups: devops,hsbc
    default_user: ec2-user
    sudoers_template_file: templates/rhel_linux_users_sudoers.j2
  when: ansible_distribution == 'RedHat'

- name: Create Digital User Groups
  group:
    name: '{{ item }}'
  with_items:
    - hsbc
    - devops

- name: Create HSBC User
  user:
    name: hsbc
    shell: /bin/bash
    group: hsbc

- name: Create DevOps User
  user:
    name: devops
    shell: /bin/bash
#    group: hsbc
    groups: '{{ devops_user_groups }}'

- name: Create devops user .ssh directory
  file:
    path: /home/devops/.ssh
    state: directory
    mode: 0700
    owner: devops
    group: devops

- name: Set Facts
  set_fact:
    sudo_user: devops
    sudoers_file: /etc/sudoers.d/99-hsbc-users

- name: Set authorized_keys for devops user
  copy:
    src: '/home/{{ default_user }}/.ssh/authorized_keys'
    remote_src: yes
    dest: /home/devops/.ssh/authorized_keys
    mode: 0600
    owner: devops
    group: devops

- name: Prepare sudoers user file
  template:
    src: '{{ sudoers_template_file }}'
    dest: '{{ sudoers_file }}'

- block:
    - name: Validate sudoers
      command: visudo -c -q -f {{ sudoers_file }}

  rescue:
    - name: Remove the broken sudoers file
      file:
        path: '{{ sudoers_file }}'
        state: absent

#- name: Disable default user account
#  user:
#    name: '{{ default_user }}'
#    state: absent
#
#- name: Remove the cloud-init sudoers file
#  file:
#    path: /etc/sudoers.d/90-cloud-init-users
#    state: absent
#
#- name: Remove the ec2-user line in sudoers
#  lineinfile:
#    path: /etc/sudoers
#    state: absent
#    regexp: '^ec2-user'
